spring.application.name=TelegramFoodbot
spring.config.import=optional:file:./local.properties

# Bot  (override in local.properties or env vars)
app.bot.token=${TELEGRAM_BOT_TOKEN}
app.bot.username=${TELEGRAM_BOT_USERNAME}
app.openai.key=${OPENAI_API_KEY}
spring.datasource.password=${DB_PASSWORD:271204}
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:foodbot}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

server.port=8080

# Logging
logging.level.org.example.telegramfoodbot=DEBUG
logging.level.org.telegram=WARN
